import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ToastProvider } from "@/components/ui/Toast";
import { ConfirmProvider } from "@/components/ui/ConfirmModal";
import FlashMessageHandler from '@/components/ui/FlashMessageHandler';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "VisualCrafters",
  description: "Generated by VCS",
  icons: {
    icon: "/Visual_Crafters_Logo_circle.png",
    shortcut: "/Visual_Crafters_Logo_circle.png",
    apple: "/Visual_Crafters_Logo_circle.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ToastProvider>
          <ConfirmProvider>
              <FlashMessageHandler />
              {children}
          </ConfirmProvider>
        </ToastProvider>
      </body>
    </html>
  );
}
